config/routes.rb
BksOnRails::Application.routes.draw do

  root 'static_pages#home'

  match '/sign_in', to:'sessions#new', via: 'get'
  match '/sign_out', to:'sessions#destroy', via: 'delete' 
  match '/manual', to: 'static_pages#manual', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]

  resources :staffers do
    resource :account, only: [:new, :create, :edit, :update]
    resource :contact, only: [:new, :create, :edit, :update]
  end

  resources :managers do
    resource :account, only: [:new, :create, :edit, :update]
    resource :contact , only: [:new, :create, :edit, :update] 
  end

  resources :riders do
    resource :account, only: [:new, :create, :edit, :update]
    resource :location, only: [:new, :create, :edit, :update]
    resource :rider_rating, only: [:new, :create, :edit, :update]
    resource :qualification_set, only: [:new, :create, :edit, :update]
    resource :skill_set, only: [:new, :create, :edit, :update]
    resource :equipment_set, only: [:new, :create, :edit, :update]
    resources :assignments
    resources :shifts do
      resources :assignments
    end
    resource :toe_consent, only: [:new, :create, :complete]
    resources :conflicts
    collection do 
      get :export, :edit_statuses
      put :update_statuses 
    end
  end

  resources :restaurants do
    resource :mini_contact, only: [:new, :create, :edit, :update]
    resources :managers, only: [:new, :create, :edit, :update, :show, :destroy]
      resource :account, only: [:new, :create, :edit, :update]
    resource :work_specification, only: [:new, :create, :edit, :update]
    resource :rider_payment_info, only: [:new, :create, :edit, :update]
    resource :agency_payment_info, only: [:new, :create, :edit, :update]
    resource :equipment_set, only: [:new, :create, :edit, :update]
    resources :shifts do
      resources :assignments
    end
    collection { get :export }
  end

  resources :shifts do
    resources :assignments
    collection { get :export, :build_export, :unconfirmed, :unconfirmed_next_week, :today, :review_points }
  end

  post 'shifts/index'
  post 'restaurants/:id/shifts/index' => 'shifts#index'
  post 'riders/:id/shifts/index' => 'shifts#index'

  get "grid/shifts"
  match '/shift_grid', to: 'grid#shifts', via: 'get'
  get "grid/availability"
  match '/availability_grid', to: 'grid#availability', via: 'get'
  post "grid/send_emails" => 'grid#send_emails'

  get 'shift/hanging' => 'shifts#hanging'
  get 'shift/clone_new' => 'shifts#clone_new' 
  get 'shift/batch_new' => 'shifts#batch_new'
  post 'shift/batch_create' => 'shifts#batch_create'
  get 'shift/batch_edit' => 'shifts#batch_edit'
  post 'shift/batch_edit' => 'shifts#batch_update'
  get 'shift/build_clone_week_preview' => 'shifts#build_clone_week_preview'
  get 'shift/preview_clone_week' => 'shifts#preview_clone_week'
  post 'shift/save_clone_week' => 'shifts#save_clone_week'
  
  get 'assignment/batch_edit' => 'assignments#batch_edit'
  post 'assignment/batch_edit' => 'assignments#batch_update'
  get 'assignment/batch_edit_uniform' => 'assignments#batch_edit_uniform'
  post 'assignment/batch_edit_uniform' => 'assignments#batch_update_uniform'
  get 'assignment/resolve_obstacles' => 'assignments#request_obstacle_decisions'
  post 'assignment/resolve_obstacles' => 'assignments#resolve_obstacles'
  post 'assignment/batch_reassign' => 'assignments#batch_reassign'

  get 'conflict/build_batch_preview' => 'conflicts#build_batch_preview'
  get 'conflict/preview_batch' => 'conflicts#preview_batch'
  post 'conflict/batch_clone' => 'conflicts#batch_clone'
  get 'conflict/batch_new' => 'conflicts#batch_new'
  post 'conflict/batch_new' => 'conflicts#batch_create'
  get 'conflict/confirm_submission' => 'conflicts#confirm_submission'

  get 'rider/request_conflicts_preview' => 'riders#request_conflicts_preview'
  get 'rider/request_conflicts' => 'riders#request_conflicts'
  get 'riders/:rider_id/toe_consent/complete' => 'toe_consents#complete'  

  
  resources :conflicts

end

app/models/manager.rb
# == Schema Information
#
# Table name: managers
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class Manager < ActiveRecord::Base
  include User, Contactable # app/model/concerns/
  has_and_belongs_to_many :restaurants
    accepts_nested_attributes_for :restaurants

  def self.select_options
    self.all.joins(:contact).order("contacts.name asc").map{ |r| [ r.name, r.id ] }
  end

  def Manager.import managers_file, accounts_file, contacts_file
    accounts = Account.import accounts_file
    contacts = Contact.import contacts_file
    managers = Manager.import_self managers_file, accounts, contacts
  end

  def Manager.import_self managers_file, accounts, contacts
    path = Rails.env.test? ? "app/io/import/sample/staffers/" : "app/io/import/staffers/"
  
    managers = []
    CSV.foreach(managers_file, headers: true) do |row|
      i = $. - 2 # $. returns the INPUT_LINE_NUMBER, subtracting one produces index number
      attrs = row
        .to_hash
        .reject{ |k,v| k == 'id' }
        .merge( { account: accounts[i], contact: contacts[i] } )
      managers.push( Manager.new attrs )
    end
    managers
  end
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id         :integer          not null, primary key
#  active     :boolean
#  status     :string(255)
#  brief      :text
#  created_at :datetime
#  updated_at :datetime
#  unedited   :boolean
#

class Restaurant < ActiveRecord::Base
  include Locatable, ImportableFirstClass, Exportable
  has_one :mini_contact, dependent: :destroy
    accepts_nested_attributes_for :mini_contact
  has_one :work_specification, dependent: :destroy
    accepts_nested_attributes_for :work_specification
  has_one :rider_payment_info, dependent: :destroy
    accepts_nested_attributes_for :rider_payment_info
  has_one :equipment_need, dependent: :destroy
    accepts_nested_attributes_for :equipment_need
  has_one :agency_payment_info, dependent: :destroy
    accepts_nested_attributes_for :agency_payment_info
  has_and_belongs_to_many :managers
    accepts_nested_attributes_for :managers, allow_destroy: true
  has_many :shifts

  classy_enum_attr :status, enum: 'AccountStatus'

  validates :status, :brief, presence: true
  validates :active, inclusion: { in: [ true, false ] }


  scope :with_shifts_this_week, -> {
    includes(:shifts, :mini_contact)
    .where(
      "start > :start_t AND start < :end_t",
      {
        start_t: (Rails.env.test? ? Time.zone.local(2014,1,6,11) : Time.zone.now).beginning_of_week,
        end_t: (Rails.env.test? ? Time.zone.local(2014,1,6,11) : Time.zone.now).beginning_of_week + 1.week
      }
    )
    .order("mini_contacts.name asc")
    .to_a.uniq
  }

  EXPORT_COLUMNS = [ 'id', 'active' ]
  EXPORT_HEADERS = EXPORT_COLUMNS


  #public methods

  def name
    self.mini_contact.name
  end

  def phone
    self.mini_contact.phone
  end

  def shifts_between start_t, end_t
    self.shifts
      .where( "start > :start AND start < :end", { start: start_t, :end => end_t } )
      .order("start asc")
  end



  #class methods

  def self.select_options
    Restaurant.all.joins(:mini_contact).order("mini_contacts.name asc").map{ |r| [ r.name, r.id ] }
  end

  def self.multiselect_options
    [ [ '* All Restaurants', 'all' ] ] + self.select_options
  end

  def self.search params
    if params[:search]
      base = self.joins(:mini_contact).where('mini_contacts.name ILIKE ?', "%#{params[:search]}%")
    else
      base = self.joins(:mini_contact)
    end
    base.order('mini_contacts.name asc').page(params[:page])
  end

  private

  def parse_export_values attrs
    attrs
  end

  def self.import_children path
    #input: none
    #output Hash of Arrays of Restaurant children
      #{ minicontacts: Arr of MiniContacts, managers: Arr of Managers, ...}
    {
      mini_contacts: MiniContact.import( "#{path}mini_contacts.csv" ),
      managers: Manager.import( "#{path}managers/managers.csv", "#{path}managers/accounts.csv", "#{path}managers/contacts.csv" ),
      work_specifications: WorkSpecification.import( "#{path}work_specifications.csv" ),
      rider_payments_infos: RiderPaymentInfo.import( "#{path}rider_payment_infos.csv" ),
      agency_payment_infos: AgencyPaymentInfo.import( "#{path}agency_payment_infos.csv" ),
      equipment_needs: EquipmentNeed.import( "#{path}equipment_needs.csv" ),
      locations: Location.import( "#{path}locations.csv" )
    }
  end

  def self.import_attrs_from row_hash, c, i
    #input: Hash of Restaurant attributes, Hash of Hashes of attributes for children of Restaurants, Int (index)
    #output: Hash of Hashes of attributes for Restaurant *and* its children
    row_hash
      .reject{ |k,v| k == 'id' }
      .merge( {
        mini_contact: c[:mini_contacts][i],
        managers: [ c[:managers][i] ],
        work_specification: c[:work_specifications][i],
        rider_payment_info: c[:rider_payments_infos][i],
        agency_payment_info: c[:agency_payment_infos][i],
        equipment_need: c[:equipment_needs][i],
        location: c[:locations][i]
      } )
  end

  def self.child_export_headers
    [ 'name', 'address', 'lat', 'lng' ]
  end

  def self.child_export_cells_from restaurant
    l = restaurant.location
    [
      restaurant.mini_contact.name,
      l.address,
      l.lat,
      l.lng
    ]
  end

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  include UsersController, ContactablesController
  before_action :load_manager, only: [ :show, :edit, :update, :destroy ]

  def new
    @manager = Manager.new
    @manager.build_account # abstract to UsersController?
    @manager.build_contact # abstract to ContactablesController?

    if params[:restaurant_id]
      load_restaurants
    else
      @manager.restaurants.build
    end

    @it = @manager
  end

  def create
    @manager = Manager.new(manager_params)
    load_restaurants
    @it = @manager
    if @manager.save
      flash[:success] = "Profile created for #{@manager.contact.name}."
      redirect_to redirect_path
    else
      params.restaurant_id = @manager.restaurants.first.id
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @manager.update(manager_params)
      flash[:success] = "#{@manager.contact.name}'s profile has been updated"
      redirect_to redirect_path
    else
      render 'edit'
    end
  end

  def destroy
    @manager.destroy
    flash[:success] = "All information associated with #{@manager.contact.name} has been deleted"
    redirect_to restaurant_path(@manager.restaurant)
  end

  private

    def load_manager
      @manager = Manager.find(params[:id])
      @it = @manager
    end

    def load_restaurants
      @manager.restaurants = [ Restaurant.find(params[:restaurant_id]) ]
    end

    def refresh_restaurant(manager)
      manager.restaurant
    end

    def redirect_path
      if current_account.user == @manager
        restaurant_manager_path(@manager.restaurants.first, @manager)
      else
        restaurant_path(@manager.restaurants.first)
      end
    end

    def manager_params
      params.require(:manager).permit(account_params, contact_params, :restaurant_id)
    end
end

app/views/managers/_add_existing_manager_js.html.haml
:javascript

  $(document).ready(function(){

    var dropdown = "#{ escape_javascript( render 'managers/dropdown' ) }" // Str

    $('#add_existing_manager').click(function(){
      var num = $('.contact_fields').length + $('.manager_dropdown').length + 1
      $('#manager_fields').append('<h3>Manager '+num+'</h3>')
      $('#manager_fields').append(dropdown)
    })
  })

app/views/managers/_choose_existing_manager_js.html.haml
- #input: it, f

:javascript

  $(document).ready(function(){

    var dropdown = "#{ escape_javascript( render 'managers/dropdown' ) }" 
      , fields = "#{ escape_javascript( render 'managers/fields_in_new_restaurant', it: it, f: f ) }"

    $('#choose_existing_manager').change(function(){
      if ($(this).prop('checked')){
        $('#manager_fields').empty()
        $('#manager_fields').append(dropdown)
      }
      else{
        $('#manager_fields').empty()
        $('#manager_fields').append(fields)
      }
    })
  })

app/views/managers/_dropdown.html.haml
/ .center
/   = label_tag :existing_manager
= select_tag 'manager_ids[]', options_for_select( Manager.select_options, nil ), include_blank: true, :class => 'manager_dropdown'

app/views/managers/_fields.html.haml
.profile
  %h3 Restaurants: 
  - it.restaurants.each do |restaurant|
    %li.center= link_to restaurant.name, restaurant
  - if params[:action] == 'new'
    = render 'accounts/fields', f: f
    = hidden_field_tag :restaurant_id, it.restaurants.first.id
  = render 'contacts/fields', f: f

app/views/managers/_fields_in_edit_restaurant.html.haml
.manager_field_set
  = f.fields_for :managers, manager do |ff|
    %h3
      Manager #{i+1}
    = render 'contacts/fields', f: ff
  %br/

app/views/managers/_fields_in_new_restaurant.html.haml
.manager_field_set
  = f.fields_for :managers do |ff|
    = render 'accounts/fields', f: ff
    = render 'contacts/fields', f: ff
  %br/

app/views/managers/_fields_wrapper.html.haml
- if it.class == Restaurant
  %h3 Managers
  #manager_fields
  
    - if params[:action] == 'new'
      .checkbox.offset1
        = check_box_tag 'choose_existing_manager', 1, false, id: 'choose_existing_manager'
        = label_tag :choose_existing, 'Choose from pre-existing managers?'
      = render 'managers/choose_existing_manager_js', it: it, f: f
      = render 'managers/fields_in_new_restaurant', it: it, f: f
    
    - if params[:action] == 'edit'
      - it.managers.each_with_index do |manager, i|
        = render 'managers/fields_in_edit_restaurant', f: f, manager: manager, i:i
  
      .center
        = link_to 'Create new manager', new_restaurant_manager_path(it)
        |
        %a.anchor#add_existing_manager
          Add existing manager
      = render 'managers/add_existing_manager_js', it: it, f: f

- elsif it.class == Manager
  = render 'managers/fields', it: it, f: f

app/views/managers/_manager.html.haml
- if manager == managers.first
  %h3 Managers
%ul
  %li
    %strong Name:
    = manager.contact.name
  %li
    %strong Title:
    = manager.contact.title  
  %li
    %strong Phone:
    = manager.contact.phone
  %li
    %strong Email:
    = manager.contact.email
  = link_to 'Edit', edit_manager_path(manager.id), id: "edit_manager_#{manager.id}"
  |
  = link_to 'Delete', manager_path(manager.id), id: "delete_manager_#{manager.id}", method: :delete, data: { confirm: "Are you sure? All information associated with #{manager.contact.name} will be permanently destroyed!" }

app/views/managers/_manager_fields.html.haml
- if object.class == Restaurant
  = form.fields_for :managers do |ff|
    = ff.fields_for :contact_info do |fff|
      = fff.label :name
      = fff.text_field :name
      = fff.label :title
      = fff.text_field :title        
      = fff.label :phone
      = fff.text_field :phone
      = fff.label :email
      = fff.text_field :email
      .checkbox
        = fff.check_box :_destroy
        = fff.label :_destroy, 'Delete?'
      %br/
/ - elsif object.class == Manager
/   = form.label :restaurant
/   - if params[:restaurant_id]
/     = form.collection_select :restaurant_id, Restaurant.all, :id, :name, selected: params[:restaurant_id]
/   - else
/     = form.collection_select :restaurant_id, Restaurant.all, :id, :name
/   = form.fields_for :contact_info do |ff|
/     = ff.label :name
/     = ff.text_field :name
/     = ff.label :title
/     = ff.text_field :title        
/     = ff.label :phone
/     = ff.text_field :phone
/     = ff.label :email
/     = ff.text_field :email

app/views/managers/edit.html.haml
- provide(:title, 'Edit Manager')
%h1 Edit Manager
.row
  .span6.offset3
    = form_for [@restaurant, @manager] do |f|
      = render 'shared/error_messages', object: f.object
      = render 'managers/fields', f: f, it: @it
      .center
        = f.submit "Save Changes", class: "btn btn-primary"

app/views/managers/new.html.haml
- provide(:title, 'Create Manager')
%h1 Create Manager
.row
  .span6.offset3
    = form_for [@restaurant, @manager] do |f|
      = render 'shared/error_messages', object: f.object
      = render 'managers/fields', f: f, it: @it
      %br/
      .center
        = f.submit "Create Manager", class: "btn btn-large btn-primary"

        

app/views/managers/show.html.haml
- provide(:title, @manager.contact.name)
.profile
  = render 'users/profile_header', it: @it
  .row
    .span10.offset1
      %h3 Contact Info
      %ul
        %li 
          %strong 
            Phone: 
          = @manager.contact.phone
        %li 
          %strong
            Email: 
          = @manager.contact.email
  .row
    %p.center
      - if can? :manage, Manager
        = link_to 'Edit', edit_restaurant_manager_path(@manager.restaurant, @manager)
        | 
        = link_to "Delete", @manager, method: :delete, data: { confirm: "Are you sure? All information associated with #{@manager.name} will be permanently destroyed!" }    