config/routes.rb
BksOnRails::Application.routes.draw do

  root 'static_pages#home'

  match '/sign_in', to:'sessions#new', via: 'get'
  match '/sign_out', to:'sessions#destroy', via: 'delete' 
  match '/manual', to: 'static_pages#manual', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]

  resources :staffers do
    resource :account, only: [:new, :create, :edit, :update]
    resource :contact, only: [:new, :create, :edit, :update]
  end

  resources :managers do
    resource :account, only: [:new, :create, :edit, :update]
    resource :contact , only: [:new, :create, :edit, :update] 
  end

  resources :riders do
    resource :account, only: [:new, :create, :edit, :update]
    resource :location, only: [:new, :create, :edit, :update]
    resource :rider_rating, only: [:new, :create, :edit, :update]
    resource :qualification_set, only: [:new, :create, :edit, :update]
    resource :skill_set, only: [:new, :create, :edit, :update]
    resource :equipment_set, only: [:new, :create, :edit, :update]
    resources :assignments
    resources :shifts do
      resources :assignments
    end
    resource :toe_consent, only: [:new, :create, :complete]
    resources :conflicts
    collection do 
      get :export, :edit_statuses
      put :update_statuses 
    end
  end

  resources :restaurants do
    resource :mini_contact, only: [:new, :create, :edit, :update]
    resources :managers, only: [:new, :create, :edit, :update, :show, :destroy]
      resource :account, only: [:new, :create, :edit, :update]
    resource :work_specification, only: [:new, :create, :edit, :update]
    resource :rider_payment_info, only: [:new, :create, :edit, :update]
    resource :agency_payment_info, only: [:new, :create, :edit, :update]
    resource :equipment_set, only: [:new, :create, :edit, :update]
    resources :shifts do
      resources :assignments
    end
    collection { get :export }
  end

  resources :shifts do
    resources :assignments
    collection { get :export, :build_export, :unconfirmed, :unconfirmed_next_week, :today, :review_points }
  end

  post 'shifts/index'
  post 'restaurants/:id/shifts/index' => 'shifts#index'
  post 'riders/:id/shifts/index' => 'shifts#index'

  get "grid/shifts"
  match '/shift_grid', to: 'grid#shifts', via: 'get'
  get "grid/availability"
  match '/availability_grid', to: 'grid#availability', via: 'get'
  post "grid/send_emails" => 'grid#send_emails'

  get 'shift/hanging' => 'shifts#hanging'
  get 'shift/clone_new' => 'shifts#clone_new' 
  get 'shift/batch_new' => 'shifts#batch_new'
  post 'shift/batch_create' => 'shifts#batch_create'
  get 'shift/batch_edit' => 'shifts#batch_edit'
  post 'shift/batch_edit' => 'shifts#batch_update'
  get 'shift/build_clone_week_preview' => 'shifts#build_clone_week_preview'
  get 'shift/preview_clone_week' => 'shifts#preview_clone_week'
  post 'shift/save_clone_week' => 'shifts#save_clone_week'
  
  get 'assignment/batch_edit' => 'assignments#batch_edit'
  post 'assignment/batch_edit' => 'assignments#batch_update'
  get 'assignment/batch_edit_uniform' => 'assignments#batch_edit_uniform'
  post 'assignment/batch_edit_uniform' => 'assignments#batch_update_uniform'
  get 'assignment/resolve_obstacles' => 'assignments#request_obstacle_decisions'
  post 'assignment/resolve_obstacles' => 'assignments#resolve_obstacles'
  post 'assignment/batch_reassign' => 'assignments#batch_reassign'

  get 'conflict/build_batch_preview' => 'conflicts#build_batch_preview'
  get 'conflict/preview_batch' => 'conflicts#preview_batch'
  post 'conflict/batch_clone' => 'conflicts#batch_clone'
  get 'conflict/batch_new' => 'conflicts#batch_new'
  post 'conflict/batch_new' => 'conflicts#batch_create'
  get 'conflict/confirm_submission' => 'conflicts#confirm_submission'

  get 'rider/request_conflicts_preview' => 'riders#request_conflicts_preview'
  get 'rider/request_conflicts' => 'riders#request_conflicts'
  get 'riders/:rider_id/toe_consent/complete' => 'toe_consents#complete'  

  
  resources :conflicts

end

app/models/staffer.rb
# == Schema Information
#
# Table name: staffers
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class Staffer < ActiveRecord::Base
  include User, Contactable, ImportableFirstClass # ../concerns/user.rb

  scope :tess, -> { joins(:contact).where("contacts.email = ?", "tess@bkshift.com").first }

  # def Staffer.email_conflict_notification rider, conflicts, week_start, notes
  #   mailed = StafferMailer.conflict_notification( rider, conflicts, week_start ).deliver
  # end

  # class methods

  def self.select_options
    self.all.joins(:contact).order("contacts.name asc").map{ |r| [ r.name, r.id ] }
  end

  def self.import_children path
    #input: none
    #output Hash of Arrays of Staffer children 
      #{ accounts: Arr of Accounts, contacts: Arr of Contacts,  ...}
    { 
      accounts: Account.import( "#{path}accounts.csv" ),
      contacts: Contact.import( "#{path}contacts.csv" )
    }
  end

  def self.import_attrs_from row_hash, c, i
    #input: Hash of Staffer attributes, Hash of Hashes of attributes for children of Restaurants, Int (index)
    #output: Hash of Hashes of attributes for Staffer *and* its children
    row_hash
      .reject{ |k,v| k == 'id' }
      .merge( {
        account: c[:accounts][i],
        contact: c[:contacts][i]
      } )
  end



end

app/controllers/staffers_controller.rb
class StaffersController < ApplicationController
  include UsersController, ContactablesController
  before_action :load_staffer, only: [:show, :edit, :update, :destroy]

  def new
    @staffer = Staffer.new
    @staffer.build_account #abstract?
    @staffer.build_contact #abstract?
    @it = @staffer
  end

  def create
    @staffer = Staffer.new(staffer_params)
    @it = @staffer
    if @staffer.save
      flash[:success] = "Profile created for #{@staffer.contact.name}."
      redirect_to @staffer
    else
      render 'new'
    end
  end

  def show
  end

  def index
    @staffers = Staffer.all
  end

  def edit
  end

  def update
    @staffer.update(staffer_params)
    if @staffer.save
      flash[:success] = "#{@staffer.contact.name}'s profile has been updated."
      redirect_to @staffer
    else
      render 'edit'
    end    
  end

  def destroy
    @staffer.destroy
    flash[:success] = "All information associated with #{@staffer.contact.name} has been deleted"
    redirect_to staffers_path
  end

  private

    def load_staffer
      @staffer = Staffer.find(params[:id])
      @it = @staffer
    end

    def staffer_params
        params.require(:staffer).permit(account_params, contact_params)
    end
end

app/views/staffers/_edit_button.html.haml
= link_to 'Edit Profile', edit_staffer_path(@staffer)

app/views/staffers/_staffer.html.haml
.profile
  %li
    %h2
      = gravatar_for staffer.contact, size: 40
      = link_to staffer.contact.name, staffer
      %br
      = staffer.contact.title

app/views/staffers/_staffer_form.html.haml
.row
  .span6.offset3
    = form_for(@staffer) do |f|
      = render 'shared/error_messages', object: f.object
      - if params[:action] == 'new'
        = render 'accounts/fields', f: f
      = render 'contacts/fields', f: f
      .center
        - button_text = params[:action] == 'new' ? 'Create Staffer' : 'Save Changes'
        = f.submit button_text, class: "btn btn-large btn-primary"

app/views/staffers/edit.html.haml
- provide(:title, 'Edit Staffer')
%h1 Edit #{@staffer.contact.name}'s Profile
.profile
  = render 'staffer_form'
  .row
    .span6 
    = gravatar_for @staffer.contact, size: 80
    = link_to 'Edit avatar', 'http://gravatar.com/emails', target: '_blank'

app/views/staffers/index.html.haml
- provide(:title, 'BK Shift Staff')
.row
  .span10.offset1
    %h1 BK Shift Staff
    %section
      %ul.staff
        = render @staffers
    .edit 
      .center
        = link_to 'Create new staffer', new_staffer_path, class: 'btn btn-large btn-primary'

app/views/staffers/new.html.haml
- provide(:title, 'Create Staffer')
%h1 Create Staffer
= render 'staffer_form'    

app/views/staffers/show.html.haml
- provide(:title, @staffer.name)
.profile
  = render '/users/profile_header', it: @it
  .row
    .span10.offset1
      = render @staffer.contact
  .row
    %p.center
      - if can? :manage, Staffer
        = link_to 'Edit', edit_staffer_path(@staffer)
        | 
        = link_to "Delete", @staffer, method: :delete, data: { confirm: "Are you sure? All information associated with #{@staffer.name} will be permanently destroyed!" }
        |
      = link_to "All Staffers", staffers_path
          