config/routes.rb
BksOnRails::Application.routes.draw do

  root 'static_pages#home'

  match '/sign_in', to:'sessions#new', via: 'get'
  match '/sign_out', to:'sessions#destroy', via: 'delete' 
  match '/manual', to: 'static_pages#manual', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]

  resources :staffers do
    resource :account, only: [:new, :create, :edit, :update]
    resource :contact, only: [:new, :create, :edit, :update]
  end

  resources :managers do
    resource :account, only: [:new, :create, :edit, :update]
    resource :contact , only: [:new, :create, :edit, :update] 
  end

  resources :riders do
    resource :account, only: [:new, :create, :edit, :update]
    resource :location, only: [:new, :create, :edit, :update]
    resource :rider_rating, only: [:new, :create, :edit, :update]
    resource :qualification_set, only: [:new, :create, :edit, :update]
    resource :skill_set, only: [:new, :create, :edit, :update]
    resource :equipment_set, only: [:new, :create, :edit, :update]
    resources :assignments
    resources :shifts do
      resources :assignments
    end
    resource :toe_consent, only: [:new, :create, :complete]
    resources :conflicts
    collection do 
      get :export, :edit_statuses
      put :update_statuses 
    end
  end

  resources :restaurants do
    resource :mini_contact, only: [:new, :create, :edit, :update]
    resources :managers, only: [:new, :create, :edit, :update, :show, :destroy]
      resource :account, only: [:new, :create, :edit, :update]
    resource :work_specification, only: [:new, :create, :edit, :update]
    resource :rider_payment_info, only: [:new, :create, :edit, :update]
    resource :agency_payment_info, only: [:new, :create, :edit, :update]
    resource :equipment_set, only: [:new, :create, :edit, :update]
    resources :shifts do
      resources :assignments
    end
    collection { get :export }
  end

  resources :shifts do
    resources :assignments
    collection { get :export, :build_export, :unconfirmed, :unconfirmed_next_week, :today, :review_points }
  end

  post 'shifts/index'
  post 'restaurants/:id/shifts/index' => 'shifts#index'
  post 'riders/:id/shifts/index' => 'shifts#index'

  get "grid/shifts"
  match '/shift_grid', to: 'grid#shifts', via: 'get'
  get "grid/availability"
  match '/availability_grid', to: 'grid#availability', via: 'get'
  post "grid/send_emails" => 'grid#send_emails'

  get 'shift/hanging' => 'shifts#hanging'
  get 'shift/clone_new' => 'shifts#clone_new' 
  get 'shift/batch_new' => 'shifts#batch_new'
  post 'shift/batch_create' => 'shifts#batch_create'
  get 'shift/batch_edit' => 'shifts#batch_edit'
  post 'shift/batch_edit' => 'shifts#batch_update'
  get 'shift/build_clone_week_preview' => 'shifts#build_clone_week_preview'
  get 'shift/preview_clone_week' => 'shifts#preview_clone_week'
  post 'shift/save_clone_week' => 'shifts#save_clone_week'
  
  get 'assignment/batch_edit' => 'assignments#batch_edit'
  post 'assignment/batch_edit' => 'assignments#batch_update'
  get 'assignment/batch_edit_uniform' => 'assignments#batch_edit_uniform'
  post 'assignment/batch_edit_uniform' => 'assignments#batch_update_uniform'
  get 'assignment/resolve_obstacles' => 'assignments#request_obstacle_decisions'
  post 'assignment/resolve_obstacles' => 'assignments#resolve_obstacles'
  post 'assignment/batch_reassign' => 'assignments#batch_reassign'

  get 'conflict/build_batch_preview' => 'conflicts#build_batch_preview'
  get 'conflict/preview_batch' => 'conflicts#preview_batch'
  post 'conflict/batch_clone' => 'conflicts#batch_clone'
  get 'conflict/batch_new' => 'conflicts#batch_new'
  post 'conflict/batch_new' => 'conflicts#batch_create'
  get 'conflict/confirm_submission' => 'conflicts#confirm_submission'

  get 'rider/request_conflicts_preview' => 'riders#request_conflicts_preview'
  get 'rider/request_conflicts' => 'riders#request_conflicts'
  get 'riders/:rider_id/toe_consent/complete' => 'toe_consents#complete'  

  
  resources :conflicts

end

app/models/conflict.rb
# == Schema Information
#
# Table name: conflicts
#
#  id         :integer          not null, primary key
#  period     :string(255)
#  rider_id   :integer
#  created_at :datetime
#  updated_at :datetime
#  start      :datetime
#  end        :datetime
#

class Conflict < ActiveRecord::Base
  include Timeboxable, BatchUpdatable

  belongs_to :rider

  validates :rider_id, presence: true

  def list_time
    "#{self.start.strftime("%A")} #{self.period.text.upcase}"
  end

end

app/controllers/conflicts_controller.rb
class ConflictsController < ApplicationController
  include Paths, Sortable

  before_action :load_conflict, only: [ :edit, :update, :show, :destroy ]
  before_action :load_caller # callbacks: load_rider (if applicable)
  before_action :load_base_path
  before_action :load_form_args, only: [ :edit, :update ]
  before_action :load_conflicts, only: [ :index ]
  # before_action :load_rider, only: [ :index, :destroy ]

  def new
    @conflict = Conflict.new(start: params[:start], :end => params[:end])
    load_form_args
  end

  def create
    @conflict = Conflict.new(conflict_params.except(:base_path))
    load_form_args
    if @conflict.save
      flash[:success] = "Created conflict for #{@conflict.rider.contact.name}"
      redirect_to @base_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @conflict.update(conflict_params.except(:base_path))
    if @conflict.save
      flash[:success] = "Edited conflict for #{@conflict.rider.contact.name}"
      redirect_to @base_path
    else
      render 'edit'
    end
  end

  def show
  end

  def index
    @conflict_table = Table.new(:conflict, @conflicts, @caller, @base_path, nil)
  end

  def destroy
    @conflict.destroy
    flash[:success] = "Conflict deleted"
    path = @base_path ? @base_path : @conflict_paths[:index]
    redirect_to path
  end

  def build_batch_preview
    render 'build_batch_preview'
    # view has dropdown for rider & start_t, gets #preview_batch
  end

  def preview_batch
    @rider = Rider.find(params[:rider_id])
    @it = staffer_signed_in? ? @rider.name : 'you'
    @its = staffer_signed_in? ? "#{@it}'s" : 'your'

    @this_week_start = Time.zone.parse params[:week_start]
    @next_week_start = @this_week_start + 1.week
    this_week_end = @this_week_start + 1.week

    old_conflicts = @rider.conflicts_between(@this_week_start, this_week_end)
    @conflicts = Conflict.clone(old_conflicts).map { |c| c.increment_by(1.week) }

    @base_path = staffer_signed_in? ? @base_path : '/conflict/confirm_submission'
    @new_batch_query = { rider_id: @rider.id, week_start: @next_week_start, base_path: @base_path }.to_query
    
    render 'preview_batch'
    # view posts to #batch_create (w/ conflicts params) or gets #batch_new (w/ rider & start_t params)
    # is the same as email view
  end

  def batch_clone
    conflicts = Conflict.batch_from_params(params[:conflicts])
    week_start = Time.zone.parse params[:week_start]
    rider = Rider.find(params[:rider_id])

    do_batch_create conflicts, week_start, rider
  end

  def batch_new
    @rider = Rider.find(params[:rider_id])
    @week_start = Time.zone.parse params[:week_start]

    render 'batch_new'
    # view posts to do_batch_new with params { rider_id: , week_start: , period_indices }
  end

  def batch_create
    rider = Rider.find(params[:rider_id].to_i)
    week_start = Time.zone.parse params[:week_start]
    period_indices = ( params[:period_indices] || [] ).map(&:to_i)
    conflicts = parse_new_batch rider, week_start, period_indices
    notes = params[:notes]

    do_batch_create conflicts, week_start, rider, notes
  end

    def parse_new_batch rider, week_start, period_indices
      #input: Datetime, Arr of Ints
      #output: Arr of Conflicts
      period_indices.map do |i|
        day_offset = i/2 # day offset increments by one every time i increases by 2
        hour_offset = (i+2) % 2 == 0 ? 12 : 18 # even indices start at 12:00, odd indices start at 18:00
        start_t = week_start + day_offset.days + hour_offset.hours
        end_t = start_t +6.hours

        Conflict.new( rider_id: rider.id, start: start_t, :end => end_t )
      end
    end


  def do_batch_create conflicts, week_start, rider, notes=nil
    # conflicts = Conflict.batch_from_params(params[:conflicts])
    @errors = Conflict.batch_create conflicts
    if @errors.empty? || conflicts.empty?
      StafferMailer.conflict_notification( rider, conflicts, week_start, notes ).deliver
      flash[:success] = "#{conflicts.length} conflicts successfully created"

      redirect_to @base_path
    else
      flash[:error] = "Error creating conflicts."

      rider_id = conflicts.first[:rider_id]
      week_start = conflicts.first.start.beginning_of_week 
      query = { rider_id: rider_id, week_start: week_start, base_path: @base_path }.to_query
      
      redirect_to "/conflicts/preview_batch?#{query}"
    end
  end

  def confirm_submission
    render 'shared/confirm_submission'
  end



  private

    def load_conflict
      @conflict = Conflict.find(params[:id])
    end

    def load_caller
      if params.include? :rider_id
        @caller = :rider
        load_rider
      end
      load_root_key
    end

    def load_root_key
      @root_key = :conflict
      load_base_path
      # raise @base_path.inspect
    end

    def load_rider
      @rider = Rider.find(params[:rider_id])
    end

    def load_form_args
      case @caller
      when :rider
        @form_args = [ @rider, @conflict ]
      when nil
        @form_args = @conflict
      end
    end

    def load_conflicts
      case @caller
      when :rider
        base = Conflict.where("conflicts.rider_id = ?", params[:rider_id])       
      when nil
        base = Conflict.all
      end
      @conflicts = base
        .joins( rider: :contact)
        .page(params[:page])
        .order(sort_column + " " + sort_direction)
    end

    def conflict_params
      params.require(:conflict).permit(:id, :start, :end, :period, :rider_id, :base_path, :start)
    end
end

app/views/conflicts/_conflict.html.haml
%h3 Conflict Details
%ul
  %li
    %strong Rider:
    = conflict.rider.contact.name
  %li
    %strong Start:
    = conflict.start.strftime("%m/%d | %I:%M%p")
  %li
    %strong End:
    = conflict.end.strftime("%I:%M%p")
  %li
    %strong Period:
    = conflict.period.text

app/views/conflicts/_fields.html.haml
= render 'shared/error_messages', object: f.object
/Rider
- if @caller == :rider
  %p
    %strong
      Rider: 
    = @rider.contact.name
  = f.hidden_field :rider_id, value: @rider.id
- else
  = f.label :rider
  = f.select :rider_id, Rider.select_options, include_blank: true
/Start
.datepicker
  = f.label :start
  = f.datetime_select :start, minute_step: 30, ampm: true
  /End
  = f.label :end
  = f.datetime_select :end, minute_step: 30, ampm: true
/Root Path
= f.hidden_field :base_path, value: @base_path

app/views/conflicts/_review_list.html.haml
%ul
  - if @conflicts.empty?
    %li 
      [ NONE ]
  - else
    - @conflicts.each do |conflict|
      %li= conflict.list_time

app/views/conflicts/batch_new.html.haml
- provide(:title, 'New Scheduling Conflicts')
- next_week = @week_start.strftime("%-m/%-d") + ' - ' + (@week_start + 6.days).strftime("%-m/%-d")

%h1
  = "New Conflicts for #{@rider.name}"

.row
  .span6.offset3
    %p.center
      %strong
        = "When are you *not* available to work next week (#{next_week})? " 
    %p.center
      (AM indicates roughly 8am-5pm, PM indicates roughly 5pm-12am)
    = form_tag '/conflict/batch_new', method: :post do
      /Rider
      = hidden_field_tag 'rider_id', @rider.id
      /Week Start
      = hidden_field_tag 'week_start', @week_start
      /Periods
      .row
        .span2.offset2
          - 14.times do |i|
            %div{ id: "period_#{i}", :class => "checkbox" }
              - day_index = i/2 # increments by 1 for every increment of 2 in i
              - period_index =  (i+2) % 2 == 0 ? 0 : 1 # 0 for even i, 1 for odd
              = check_box_tag 'period_indices[]', i
              = label_tag :period, "#{Week::DAYS[day_index]} #{Week::PERIODS[period_index]}"
      /Notes
      .row
        = label_tag :notes
        = text_area_tag 'notes', "Please enter any notes about your availability (irregular times, etc.) here"
      /Basepath
      = hidden_field_tag :base_path, @base_path
      /Submit
      .row.center
        %p
        %p
          = submit_tag 'Submit', :class => 'btn btn-primary'
        

app/views/conflicts/build_batch_preview.html.haml
- provide(:title, 'Build Conflict Batch')

%h1 Build Conflict Batch
.row.profile
  .span8.offset2
    = form_tag '/conflict/preview_batch', method: :get do 
      .row
        /Rider
        .span4
          = label_tag :rider
          = select_tag 'rider_id', options_for_select(Rider.select_options, nil ), include_blank: true
        /Week Start
        .span4
          - default_week_start = Time.zone.now.beginning_of_week
          = render '/shared/datepicker', label: 'Monday of Week to Clone:', id: "week_start", name: 'week_start', start_i: default_week_start.to_i, start_str: default_week_start.strftime("%B %e, %Y")
      /Submit
      .row
        %p.center
          = submit_tag 'Submit', :class => 'btn btn-primary'

app/views/conflicts/confirm_submission.html.haml
- provide(:title, "Submission Confirmation")

%h1
  Submission Confirmation
%p
  We received your submission. Thank you!

app/views/conflicts/edit.html.haml
- case @caller
- when :rider
  %h1 Edit Conflict for #{@rider.contact.name}
- when nil
  %h1 Edit Conflict
.row
  .span6.offset3
    = form_for @form_args do |f|
      = render 'conflicts/fields', f: f
      .center
        = f.submit "Save changes", class: "btn btn-primary"
        = link_to 'Delete', conflict_path(@conflict, base_path: @base_path), method: :delete, data: { confirm: 'Are you sure?' }, base_path: @base_path, class: "btn btn-primary"

app/views/conflicts/index.html.haml
- provide(:title, "Conflicts" )

/Arguments
- case @caller
- when :rider
  - header = "Conflicts for #{@rider.contact.name}"
  - span = "span6 offset3"
  - rider_link = link_to "#{@rider.contact.name}'s profile", rider_path(@rider)
- when nil
  - header = "Conflicts"
  - span = "span8 offset2"
  - rider_link = link_to 'Rider list', riders_path

- create_conflict_link = link_to 'Create conflict', new_path
- hot_links = create_conflict_link + ' | ' + rider_link

/Header
%h1 
  = header

/Hot Links 
%p.center
  = hot_links

/Pagination
.center
  = will_paginate @conflicts

/Table
.row
  %div{ class: span }
    = render 'layouts/table', table: @conflict_table
    / = render 'conflicts/table/wrapper', conflicts: @conflicts

/Pagination
.center
  = will_paginate @conflicts

/Hot Links
%p.center
  = hot_links

app/views/conflicts/new.html.haml
- case @caller
- when :rider
  %h1 New Conflict for #{@rider.contact.name}
- when nil
  %h1 New Conflict
.row
  .span6.offset3
    = form_for @form_args do |f|
      = render 'conflicts/fields', f: f
      .center
        = f.submit "Create conflict", class: "btn btn-primary"

app/views/conflicts/preview_batch.html.haml
- provide(:title, "Conflicts for #{@rider.name}" )

- #args: @it, @its, @this_week_start, @next_week_start
- m_d = lambda{ |time| time.strftime( "%-m/%-d" ) }
- this_week = m_d.call(@this_week_start) + ' - ' + m_d.call(@this_week_start + 6.days)
- next_week = m_d.call(@next_week_start) + ' - ' + m_d.call(@next_week_start + 6.days)

/Header
%h1
  = "Conflicts for #{@rider.name}"
/Body
.row.profile
  .span6.offset3
    /Batch Review
    %p 
      = "This week (#{this_week}) #{@it} had the following conflicts:"
    = render 'conflicts/review_list'
    / Choice
    %p
      %strong
        = "Click below to indicate if #{@its} conflicts next week (#{next_week}) will be:"
      /Same
      = form_tag "/conflict/batch_clone", method: :post do
        - @conflicts.each do |conflict|
          - attrs = conflict.attributes.slice('rider_id', 'start', 'end')
          - attrs.each do |k,v|
            = hidden_field_tag "conflicts[][#{k}]", v 
        = hidden_field_tag :week_start, @next_week_start
        = hidden_field_tag :rider_id, @rider.id
        = hidden_field_tag :base_path, @base_path    
        %p.center
          = submit_tag 'Same', :class => 'btn btn-primary'
          /Different
          = link_to 'Different', "/conflict/batch_new?#{@new_batch_query}", :class => 'btn btn-primary'

app/views/conflicts/show.html.haml
- provide(:title, 'Assignment Details')
.profile
  .row
    .span6.offset3
      = render @conflict, rider: @conflict.rider